/**
 * QuickBooks Online integration helper.
 *
 * Mirrors the shape of `lib/integrations/google-calendar.ts` deliberately:
 *
 *   - One `Resource` row per (tenant, department, user) holds the OAuth
 *     connection (refresh_token, access_token, realmId, expiry). Stored as
 *     envelope-encrypted ciphertext via `lib/crypto.ts`.
 *   - Three exported functions cover the entire lifecycle the rest of the
 *     codebase needs: start an OAuth handshake (`createQuickBooksOAuthClient`),
 *     persist a finished handshake (`saveQuickBooksConnection`), and get a
 *     usable, freshly-refreshed access token (`getQuickBooksAccessToken`).
 *   - All MCP-server-side concerns (rate limit, RBAC, audit) live elsewhere;
 *     this file only owns the integration's network surface and token
 *     storage.
 *
 * The Intuit OAuth spec:
 *   - Authorize:    https://appcenter.intuit.com/connect/oauth2
 *   - Token URL:    https://oauth.platform.intuit.com/oauth2/v1/tokens/bearer
 *   - API base:     https://sandbox-quickbooks.api.intuit.com/v3/company/{realmId}/...
 *                   (production = quickbooks.api.intuit.com)
 *
 * Refresh-token lifetime: 100 days (sliding). The access_token is 1 hour.
 * We refresh proactively whenever <5 min remain. If a refresh token expires
 * (e.g. user revoked), the next call throws a typed error so the UI can
 * surface "reconnect QuickBooks" instead of a 500.
 */

import { db } from '@/lib/db';
import { decryptResourceData, encrypt } from '@/lib/crypto';

const RESOURCE_NAME = 'quickbooks_connection';

const AUTHORIZE_URL = 'https://appcenter.intuit.com/connect/oauth2';
const TOKEN_URL = 'https://oauth.platform.intuit.com/oauth2/v1/tokens/bearer';
const REVOKE_URL =
  'https://developer.api.intuit.com/v2/oauth2/tokens/revoke';

export const QUICKBOOKS_SCOPES = [
  'com.intuit.quickbooks.accounting',
  'openid',
  'profile',
  'email',
];

export interface QuickBooksScope {
  tenantId: string;
  departmentId: string;
  userId: string;
}

interface StoredQuickBooksConnection {
  refreshToken: string;
  accessToken?: string;
  /** ms-since-epoch */
  accessTokenExpiresAt?: number;
  /** Intuit company id (a.k.a. realmId) — required on every API call. */
  realmId: string;
  /** Which Intuit environment ('sandbox' | 'production') minted these tokens. */
  environment: 'sandbox' | 'production';
  connectedAt: string;
}

export class QuickBooksNotConnectedError extends Error {
  constructor() {
    super(
      'QuickBooks is not connected for this user. Visit /api/integrations/quickbooks/start first.',
    );
    this.name = 'QuickBooksNotConnectedError';
  }
}

export class QuickBooksAuthExpiredError extends Error {
  constructor() {
    super(
      'QuickBooks refresh token is no longer accepted by Intuit. The user must reconnect.',
    );
    this.name = 'QuickBooksAuthExpiredError';
  }
}

function requiredEnv(name: string): string {
  const v = process.env[name];
  if (!v) {
    throw new Error(`${name} is required for QuickBooks integration`);
  }
  return v;
}

function getEnvironment(): 'sandbox' | 'production' {
  const v = (process.env.QUICKBOOKS_ENVIRONMENT ?? 'sandbox').toLowerCase();
  return v === 'production' ? 'production' : 'sandbox';
}

function getApiBase(env: 'sandbox' | 'production'): string {
  return env === 'production'
    ? 'https://quickbooks.api.intuit.com'
    : 'https://sandbox-quickbooks.api.intuit.com';
}

function basicAuthHeader(): string {
  const clientId = requiredEnv('QUICKBOOKS_CLIENT_ID');
  const clientSecret = requiredEnv('QUICKBOOKS_CLIENT_SECRET');
  return (
    'Basic ' +
    Buffer.from(`${clientId}:${clientSecret}`, 'utf8').toString('base64')
  );
}

// -------------------- OAuth start --------------------

export interface QuickBooksAuthUrl {
  url: string;
  state: string;
}

/**
 * Build the Intuit consent URL. `state` is generated by the caller (the route
 * handler) so it can verify the callback came from a flow we started — we sign
 * it with the user's id to mitigate CSRF-on-OAuth and to bind a callback to
 * the originating session.
 */
export function buildAuthorizeUrl(state: string): string {
  const clientId = requiredEnv('QUICKBOOKS_CLIENT_ID');
  const redirectUri = requiredEnv('QUICKBOOKS_REDIRECT_URI');
  const params = new URLSearchParams({
    client_id: clientId,
    redirect_uri: redirectUri,
    response_type: 'code',
    scope: QUICKBOOKS_SCOPES.join(' '),
    state,
  });
  return `${AUTHORIZE_URL}?${params.toString()}`;
}

// -------------------- OAuth callback --------------------

interface IntuitTokenResponse {
  access_token: string;
  refresh_token: string;
  expires_in: number; // seconds, typically 3600
  x_refresh_token_expires_in: number; // seconds, ~100 days
  token_type: string; // 'bearer'
}

async function exchangeCodeForTokens(
  code: string,
): Promise<IntuitTokenResponse> {
  const redirectUri = requiredEnv('QUICKBOOKS_REDIRECT_URI');
  const res = await fetch(TOKEN_URL, {
    method: 'POST',
    headers: {
      Authorization: basicAuthHeader(),
      'Content-Type': 'application/x-www-form-urlencoded',
      Accept: 'application/json',
    },
    body: new URLSearchParams({
      grant_type: 'authorization_code',
      code,
      redirect_uri: redirectUri,
    }).toString(),
  });
  if (!res.ok) {
    const text = await res.text();
    throw new Error(
      `Intuit token exchange failed (${res.status}): ${text.slice(0, 500)}`,
    );
  }
  return (await res.json()) as IntuitTokenResponse;
}

async function refreshAccessToken(
  refreshToken: string,
): Promise<IntuitTokenResponse> {
  const res = await fetch(TOKEN_URL, {
    method: 'POST',
    headers: {
      Authorization: basicAuthHeader(),
      'Content-Type': 'application/x-www-form-urlencoded',
      Accept: 'application/json',
    },
    body: new URLSearchParams({
      grant_type: 'refresh_token',
      refresh_token: refreshToken,
    }).toString(),
  });
  if (res.status === 400 || res.status === 401) {
    throw new QuickBooksAuthExpiredError();
  }
  if (!res.ok) {
    const text = await res.text();
    throw new Error(
      `Intuit token refresh failed (${res.status}): ${text.slice(0, 500)}`,
    );
  }
  return (await res.json()) as IntuitTokenResponse;
}

// -------------------- Resource I/O --------------------

async function findConnection(scope: QuickBooksScope) {
  return db.resource.findFirst({
    where: {
      tenantId: scope.tenantId,
      departmentId: scope.departmentId,
      createdBy: scope.userId,
      name: RESOURCE_NAME,
    },
  });
}

function parseConnectionData(raw: string): StoredQuickBooksConnection | null {
  try {
    const parsed = JSON.parse(raw) as Partial<StoredQuickBooksConnection>;
    if (
      !parsed ||
      typeof parsed.refreshToken !== 'string' ||
      typeof parsed.realmId !== 'string'
    ) {
      return null;
    }
    const environment: 'sandbox' | 'production' =
      parsed.environment === 'production' ? 'production' : 'sandbox';
    return {
      refreshToken: parsed.refreshToken,
      accessToken:
        typeof parsed.accessToken === 'string' ? parsed.accessToken : undefined,
      accessTokenExpiresAt:
        typeof parsed.accessTokenExpiresAt === 'number'
          ? parsed.accessTokenExpiresAt
          : undefined,
      realmId: parsed.realmId,
      environment,
      connectedAt:
        typeof parsed.connectedAt === 'string'
          ? parsed.connectedAt
          : new Date().toISOString(),
    };
  } catch {
    return null;
  }
}

async function readConnection(
  scope: QuickBooksScope,
): Promise<{ id: string; conn: StoredQuickBooksConnection } | null> {
  const row = await findConnection(scope);
  if (!row) return null;
  const plaintext = await decryptResourceData(row.data);
  const conn = parseConnectionData(plaintext);
  if (!conn) return null;
  return { id: row.id, conn };
}

async function writeConnection(
  scope: QuickBooksScope,
  conn: StoredQuickBooksConnection,
): Promise<void> {
  const encrypted = await encrypt(JSON.stringify(conn));
  const existing = await findConnection(scope);
  if (existing) {
    await db.resource.update({
      where: { id: existing.id },
      data: { data: encrypted },
    });
    return;
  }
  await db.resource.create({
    data: {
      tenantId: scope.tenantId,
      departmentId: scope.departmentId,
      createdBy: scope.userId,
      name: RESOURCE_NAME,
      data: encrypted,
    },
  });
}

// -------------------- Public lifecycle API --------------------

export async function saveQuickBooksConnection(
  scope: QuickBooksScope,
  input: { code: string; realmId: string },
): Promise<void> {
  const tokens = await exchangeCodeForTokens(input.code);
  const environment = getEnvironment();
  const conn: StoredQuickBooksConnection = {
    refreshToken: tokens.refresh_token,
    accessToken: tokens.access_token,
    accessTokenExpiresAt:
      Date.now() + Math.max(0, (tokens.expires_in - 30) * 1000),
    realmId: input.realmId,
    environment,
    connectedAt: new Date().toISOString(),
  };
  await writeConnection(scope, conn);
}

/**
 * Returns a current access token, refreshing it if it's within 5 minutes of
 * expiry. Throws `QuickBooksNotConnectedError` if there is no connection and
 * `QuickBooksAuthExpiredError` if Intuit rejects the refresh token (user must
 * reconnect).
 */
export async function getQuickBooksAccessToken(
  scope: QuickBooksScope,
): Promise<{
  accessToken: string;
  realmId: string;
  apiBase: string;
}> {
  const found = await readConnection(scope);
  if (!found) throw new QuickBooksNotConnectedError();
  const { conn } = found;

  const fiveMinutes = 5 * 60 * 1000;
  const expiresAt = conn.accessTokenExpiresAt ?? 0;
  const needsRefresh = !conn.accessToken || Date.now() > expiresAt - fiveMinutes;

  let accessToken = conn.accessToken;
  if (needsRefresh) {
    const refreshed = await refreshAccessToken(conn.refreshToken);
    accessToken = refreshed.access_token;
    const next: StoredQuickBooksConnection = {
      ...conn,
      // Intuit rotates refresh tokens occasionally; persist the new one.
      refreshToken: refreshed.refresh_token ?? conn.refreshToken,
      accessToken,
      accessTokenExpiresAt:
        Date.now() + Math.max(0, (refreshed.expires_in - 30) * 1000),
    };
    await writeConnection(scope, next);
  }

  if (!accessToken) throw new QuickBooksNotConnectedError();
  return {
    accessToken,
    realmId: conn.realmId,
    apiBase: getApiBase(conn.environment),
  };
}

export async function isQuickBooksConnected(
  scope: QuickBooksScope,
): Promise<boolean> {
  const found = await readConnection(scope);
  return !!found;
}

export async function revokeQuickBooksConnection(
  scope: QuickBooksScope,
): Promise<void> {
  const found = await readConnection(scope);
  if (!found) return;
  try {
    await fetch(REVOKE_URL, {
      method: 'POST',
      headers: {
        Authorization: basicAuthHeader(),
        'Content-Type': 'application/json',
        Accept: 'application/json',
      },
      body: JSON.stringify({ token: found.conn.refreshToken }),
    });
  } catch {
    // Best-effort: if Intuit is unreachable we still drop the local row so the
    // user isn't stuck with an unconnectable account.
  }
  await db.resource.delete({ where: { id: found.id } });
}

// -------------------- Thin REST helper --------------------

/**
 * Low-level call into the QuickBooks Online REST API. Handles auth + retry on
 * 401 (token rotated under us). Body is JSON-serialized; response is parsed
 * as JSON.
 */
export async function quickBooksFetch<T>(
  scope: QuickBooksScope,
  init: {
    path: string;
    method?: 'GET' | 'POST' | 'PUT' | 'DELETE';
    query?: Record<string, string | number | undefined>;
    body?: unknown;
  },
): Promise<T> {
  const { accessToken, realmId, apiBase } = await getQuickBooksAccessToken(scope);
  const search = new URLSearchParams({ minorversion: '70' });
  if (init.query) {
    for (const [k, v] of Object.entries(init.query)) {
      if (v !== undefined) search.set(k, String(v));
    }
  }
  const url = `${apiBase}/v3/company/${encodeURIComponent(realmId)}${init.path}?${search.toString()}`;

  const res = await fetch(url, {
    method: init.method ?? 'GET',
    headers: {
      Authorization: `Bearer ${accessToken}`,
      Accept: 'application/json',
      'Content-Type': 'application/json',
    },
    body: init.body !== undefined ? JSON.stringify(init.body) : undefined,
  });

  if (res.status === 401) {
    // Token may have been revoked or rotated. Surface a typed error so the
    // caller can mark the connection invalid.
    throw new QuickBooksAuthExpiredError();
  }
  if (!res.ok) {
    const text = await res.text();
    throw new Error(
      `QuickBooks API ${init.path} failed (${res.status}): ${text.slice(0, 500)}`,
    );
  }
  return (await res.json()) as T;
}
